### ISSUE TITLE
Check the examples by implementing the python code

### ISSUE THREAD

**Issue by DerkNiessink** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#14]
To the documentation of each class I am adding examples of how to use it. These examples have to be checked by running the Python code.

**Comment by AnneliesVlaar** [comment]
The examples are now as if they are run in a REPL (with the >>>) for example:
```
>>> checkbox = QCheckBox()
>>> checkbox.isChecked()
False
>>> checkbox.setChecked(True)
>>> checkbox.isChecked()
True
```
But if you use this in a script you won't get `True` because you have to print it. That is confusing for beginners. 
In the ECPC guide, we separate input from output. And show examples as if it is run in a script. 
Not sure if we want to have the run-button (and if it is possible) in the documentation (see https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/2) 

Or show examples like this:
```
checkbox = QCheckBox()
print(checkbox.isChecked())
```
False
```
checkbox.setChecked(True)
print(checkbox.isChecked())
```
True
